---
# tasks file for while_true_do.srv_kvm

- name: Check support for intel nesting
  stat:
    path: /sys/module/kvm_intel/parameters/nested
  register: intel_nesting_support
  tags:
    - kvm
    - virtualization

- name: Check support for amd nesting
  stat:
    path: /sys/module/kvm_amd/parameters/nested
  register: amd_nesting_support
  tags:
    - kvm
    - virtualization

- name: Configure kvm_intel Module
  template:
    src: modprobe.d.kvm_intel.conf.j2
    dest: /etc/modprobe.d/kvm_intel.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Reboot System
  when: intel_nesting_support.stat.exists == 1
  tags:
    - kvm
    - package
    - virtualization
    - system

- name: Configure kvm_amd Module
  template:
    src: modprobe.d.kvm_amd.conf.j2
    dest: /etc/modprobe.d/kvm_amd.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Reboot System
  when: amd_nesting_support.stat.exists == 1
  tags:
    - kvm
    - package
    - virtualization
    - system
