---
# tasks file for while_true_do.srv_kvm

- name: Include distribution Vars
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - kvm
    - package

- name: Manage kvm Packages
  package:
    name: "{{ wtd_srv_kvm_package }}"
    state: "{{ wtd_srv_kvm_package_state }}"
  become: true
  notify: Reboot System
  tags:
    - kvm
    - package
    - virtualization

- name: Manage libvirt Service
  service:
    name: "{{ wtd_srv_kvm_service }}"
    state: "{{ wtd_srv_kvm_service_state }}"
    enabled: "{{ wtd_srv_kvm_service_enabled }}"
  become: true
  when:
    - wtd_srv_kvm_package_state != "absent"
  tags:
    - kvm
    - libvirt
    - service
    - virtualization

- name: Include ksm Tasks
  include_tasks: ksm.yml
  when:
    - wtd_srv_kvm_package_state != "absent"
    - ansible_virtualization_type != "docker"
  tags:
    - kvm
    - ksm
    - virtualization

- name: Include kvm nested Tasks
  include_tasks: kvm-nested.yml
  when:
    - wtd_srv_kvm_package_state != "absent"
    - wtd_srv_kvm_conf_nested_enabled
  tags:
    - kvm
